export const PATTERN_COLLAPSE_STOP = 0.5;
export const PATTERN_COLLAPSE_MS = 1800;
export const PATTERN_STAR_MAP_INK_MS = 1800;

export const FIGURE3_SERVICES_DURATION_MS = 2000;

export const CRANE_CONTACT_DURATION_MS = 3000;

export const TTG_PLAYBACK_MS = 2500;
export const PH_PLAYBACK_MS = 1520;
export const INTRA_CHAPTER_DISSOLVE_MS = 600;
