export const PATTERN_COLLAPSE_MS = 1800;
export const PATTERN_STAR_MAP_INK_MS = 1800;
export const PATTERN_TOTAL_MS = PATTERN_COLLAPSE_MS + PATTERN_STAR_MAP_INK_MS;
export const PATTERN_COLLAPSE_STOP = PATTERN_COLLAPSE_MS / PATTERN_TOTAL_MS;

export const HERO_PATTERN_MOTION_MS = 900;
export const HERO_PATTERN_INK_MS = 1800;
export const HERO_PATTERN_TOTAL_MS = HERO_PATTERN_MOTION_MS + HERO_PATTERN_INK_MS;
export const HERO_PATTERN_MOTION_STOP = HERO_PATTERN_MOTION_MS / HERO_PATTERN_TOTAL_MS;

export const TERMINAL_DWELL_MS = 1000;

export const FIGURE3_SERVICES_DURATION_MS = 2600;

export const CRANE_CONTACT_DURATION_MS = 3000;

export const TTG_PLAYBACK_MS = 2500;
export const PH_PLAYBACK_MS = 1520;
export const INTRA_CHAPTER_DISSOLVE_MS = 600;
